### ISSUE TITLE
Implement golang CLI for FlyteAdmin (Flyte API's) - flytectl

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#122]
Flyte today comes with flyte-cli (python implementation) which is bundled with flytekit. We would like to implement a simple golang binary that can be installed on any client and would be used to communicate with FlyteAdmin. This would allow a standalone installation of a CLI binary.

Some of the key features that we are looking for are:
- golang binary
- installable on all platforms - delivered through brew, apt-get etc
- Self updating
- standardized interface like kubectl
    - flytectl get workflows/launchplans etc 
- Ability to add flytectl plugins for task plugins
- Ability to handle oauth2 flow, this is required as auth will soon be mandatory.
- REST/gRPC compliant.  We want to start with REST in part to mirror kubectl and in part because it's more flexible (for instance, the issues we've encountered when attempting to run Flyte Admin without SSL termination).  However, gRPC as an option will be good to have as well.

This list of features is meant only as the barebones.  We are looking more to users of Flyte for additional features or UX constructs as users naturally better able to uncover frustrations with the tooling in their daily use.

There is some more background information around auto-generated HTTP clients (from an autogenerated OpenAPI spec) in the flyteidl repo.

**Comment by wild-endeavor** [comment]
CC'ing @barakmich who has implemented other tooling already to deal with some of the shortcomings of the existing tool.

UX concerns
* Listing of workflows is not usable.  Users should be able to see workflows grouped by status for instance, probably with the running ones at the top.
* Listing should include start time, execution start time (potentially of each task, because there's no way to differentiate queueing time right now), the SHA, etc.
* The usage of filtration is not well documented and hard to remember.  It's much easier to be able to pass in a --running flag for instance to get running workflows.  Or --BlahWorkflow to scope it down to a given workflow.

Features
* For nested executions, it's useful to be able to see a tree of executions, and the status of each of the child executions.

CC @haoyuez who had some thoughts as well.  The L5 London team has also developed their own tooling in the short term.  Are there specific features that you can list Haoyue?

Thanks.

**Comment by haoyuez** [comment]
There is a documentation of the tool we developed:
https://confluence.lyft.net/pages/viewpage.action?spaceKey=Level5&title=Flyte+Monitoring+Tool

some newly added ( hasn't documented ) features like summary of status, average task durations, queueing time, etc.

**Comment by evalsocket** [comment]
@kumare3 Interested in this issue ? what is the status of the task

**Comment by kumare3** [comment]
> @kumare3 Interested in this issue ? what is the status of the task

@evalsocket great. This is partially work in progress by @brucearctor is helping with it. But I think the scope is pretty large. You both could probably drive it much faster or divide many parts of it. I would love to help breakdown parts and work on them individually if you are up to it. 

Please join this slack channel  (#flytectl) and we can discuss more in detail
https://app.slack.com/client/TN89P6GGK/C014PL3HUTF/details/top

To join slack if you have not already 
https://docs.google.com/forms/d/e/1FAIpQLSf8bNuyhy7rkm77cOXPHIzCm3ApfL7Tdo7NUs6Ej2NOGQ1PYw/viewform?pli=1

**Comment by kumare3** [comment]
Also @evalsocket @brucearctor's working on his for at - https://github.com/brucearctor/flytectl/tree/initial-commit
I think this is a large piece of work. We can sync with him to get some of this upstreamed. I am ok with this being early prototype as no one is really using it :), and we all iteratively improve it

**Comment by kumare3** [comment]
we will close this issue in favor of the project
