### ISSUE TITLE
Set "imagePullPolicy: Never" for sandbox env

### ISSUE THREAD

**Issue by apryiomka** [lyft/flyte#169]
When running flyte locally in sandbox environment, it is useful to be able to iterate on docker images quickly, build and run them in the workflows. Currently the yaml spec sets the pod's image policy to `imagePullPolicy: IfNotPresent` which would try to pull image from the actual docker registry and fail. In some orgs like ours the credentials to publish docker images to the private registry are not even available meaning the only way to test and iterate locally is to go via CI/CD pipeline with the publish step. This is extremely inefficient way to test workflows in local environment.

What i would like to be able to do is to set the `imagePullPolicy: Never` to force the local k8s instance to fall back to local images.

**Comment by kumare3** [comment]
@apryiomka doesnt, IfNotPresent imply that if you have an image locally it will not try to pull it from remote? Are you suggesting to use Never as a failure mechanism, so that if the image is not built locally, it fails instantaneously?

Moreover, do you think this is a platform level override or a per task registration parameter?
Example: In an override, we could just enforce that for a deployment of flyte it will always use `imagepullpolicy: <set by platform override>`, if no override is provided then it uses the default

Thank you for opening this issue, it is wonderful to have more users try it out and help us isolate issues

**Comment by kumare3** [comment]
On thinking more closely, imagepullpolicy never will imply that no new images will be downloaded. I do not think that is the right solution. IfNotPresent should accomplish what you really want - use local images if present. Now important caveat, that the image should be tagged correctly. 

I am going to close the issue, please open it with some additional information, if you think this is till the right approach.
