### ISSUE TITLE
[Feature - UI] Support launching single tasks

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#459]
**Motivation: Why do you think this is important?**
Single tasks are becoming first-class citizens. Just like how people can launch workflows, they should be able to launch tasks using the single tasks launch API.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [X] FlyteConsole (UI)
- [ ] Other

**Additional context**
Assumption: we will be able to use most of the UI components already developed for the launch form. If this is not the case, we should re-evaluate the priority of this work.

**Comment by schottra** [comment]
@EngHabu Do we have endpoints for launching a single task yet? If not, is there an issue tracking that work?

**Comment by EngHabu** [comment]
Yes, @katrogan can provide information about this.

**Comment by katrogan** [comment]
yep it's completed end to end and docs are here: https://github.com/lyft/flyte/blob/master/rsts/user/features/single_task_execution.rst

for the UI to trigger a single task execution you'll want to reference task rather than a launch plan in the [create execution request spec](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/admin/execution.proto#L210). (we haven't rolled out renaming the field)

**Comment by schottra** [comment]
Implemented by lyft/flyteconsole#103
Available in flyteconsole v0.13.0
