### ISSUE TITLE
Allow download of Inputs / Outputs

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#58]
It's unclear exactly what format things should be in, but for I/O types like CSV/Blob/Schema we should be able to provide a download link for the user.

Options:
 1. Convert it to a signed S3 link. This is probably not the right move because we need to verify the identity of a user before allowing them to download
 2. Convert the s3:// protocol to an actual s3 link. It would be up to the user to ensure they are assuming the correct role to be able to download the file.

Likely it will be option 2.

For things like CSV list, we have to consider how to display a list of these items.

**Comment by kumare3** [comment]
@schottra I think there are a lot of tasks assigned to you. Can you go over them once and let me know where you can use help. Also having a UX link for most of them would be great

**Comment by schottra** [comment]
@kumare3 This item doesn't have any UX design or mocks other than the thoughts listed in the description. I'm open to ideas for a good experience. 

Pretty much anything that others want to pick up is fine with me. The things marked "pri1" would need discussion first, since those are mostly major feature efforts.

**Comment by EngHabu** [comment]
Bug bankruptcy.
