### ISSUE TITLE
UI for aborted workflows is confusing

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#76]

**Comment by kumare3** [comment]
can we get an update for this? and let us improve the description

**Comment by schottra** [comment]
@kumare3 I didn't log the original issue, and I'm not sure what this bug is referring to 😞 . It seems like the details were lost when we migrated our issues over?

I would be okay closing it due to lack of information. If the original reporter wants to re-open with additional details, I'd be willing to look at it then.
