### ISSUE TITLE
sidecar task logging broken in the UI

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#93]
sidecar task logging seems to be broken in the UI:
 in the UI getting: `k8s task failed, error info not available` 
 and when following the cloudwatch links:
 `Log stream not found`

**Comment by slai** [comment]
This looks like it is occurring because the container IDs are not being matched to the correct tasks when building Cloudwatch Log URLs, leading to invalid log stream names.

The k8s log links appear to work, but they do not select the appropriate container in the UI (not sure if this is possible in the k8s console).

**Comment by kumare3** [comment]
@slai I do not thing this is possible in k8s console. And today we do not have the capability of just selecting one log link. But, I do not think this is a blocker in any way. Right now I can see the log links for container tasks.

**Comment by kumare3** [comment]
I actually see the problem, In cloudwatch for this case it should only return the base stream prefix or return all stream prefixes.

By base stream prefix i mean this
`var.log.containers.f59a48c4204204f90a80-nodeid-attempt_project-domain_containername`

**Comment by kumare3** [comment]
resolving
