### ISSUE TITLE
Workflow inputs randomly reorder themselves while I'm reading them

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#98]
When I click "View Inputs and Outputs" for a running Flyte workflow, the inputs are listed in a random order, and they _randomly reorder themselves every 10 seconds as I'm reading them_ (see attached video).

Over half the time I spend interacting with the Flyte UI is spent copying/pasting inputs from one existing workflow into the "Launch Workflow" dialog box. With this bug, the new UI is practically unusable for me.

I think the inputs should consistently display in the same order that they appear in the "Launch Workflow" dialog.

**Comment by schottra** [comment]
The random ordering is likely because the UI does not sort the properties on the object being returned from the Admin API.

The 10 second interval means it's probably related to the polling mechanism we use for fetching updated execution information while an execution is non-terminal. I'm a little surprised that it would affect rendering of the Inputs/Outputs, so I'll investigate that!

**Comment by schottra** [comment]
This is fixed by lyft/flyteconsole#24 and will be included in the [v.0.2.1](https://github.com/lyft/flyteconsole/releases/tag/v0.2.1) release.
